# spring 相关配置
spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/game_forum?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: '052018'
  ### 配置Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 1470634109
  # 发送者邮箱相关配置
  mail:
    # SMTP服务器域名
    host: smtp.163.com
    # 编码集
    default-encoding: UTF-8
    # 邮箱用户名
    username: efan0305@163.com
    # 授权码(注意不是邮箱密码！)
    password: IJSUQFXPZFFCYQDM
    # 协议：smtps
    protocol: smtps
    # 详细配置
    properties:
      mail:
        smtp:
          # 设置是否需要认证,如果为true,那么用户名和密码就必须的,
          # 如果设置false,可以不设置用户名和密码
          # (前提要知道对接的平台是否支持无密码进行访问的)
          auth: true
          # STARTTLS[1]  是对纯文本通信协议的扩展。
          # 它提供一种方式将纯文本连接升级为加密连接（TLS或SSL）
          # 而不是另外使用一个端口作加密通信。
          starttls:
            enable: true
            required: true

